[default]
optimizer = true
optimizer_runs = 20000
remappings = [
	'forge-std/=lib/forge-std/src/',
	'ds-test/=lib/ds-test/src/',
	'@morpho/data-structures/=lib/data-structures/',
	'@aave/periphery-v3/=lib/periphery-v3/',
	'@aave/core-v3/=node_modules/@aave/core-v3/',
	'@openzeppelin/=node_modules/@openzeppelin/',
	'@rari-capital/=node_modules/@rari-capital',
	'@uniswap/=node_modules/@uniswap/',
	'hardhat/=node_modules/hardhat/',
	'@contracts/=contracts/',
	'@config/=config/polygon-mainnet/aave-v3/'
]
