name: Foundry tests
description: Runs full forge test suite given a protocol and a network

inputs:
  alchemyKey:
    description: The Alchemy key giving access to a private RPC.
    required: true
  protocol:
    description: The protocol against which to run the forge test suite.
    required: true
  network:
    description: The network against which to run the forge test suite.
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Node dependencies cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: yarn-${{ hashFiles('yarn.lock') }}

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash

    - name: Install Foundry
      uses: onbjerg/foundry-toolchain@v1
      with:
        version: nightly

    - name: Foundry fork cache
      uses: actions/cache@v3
      with:
        path: "~/.foundry/cache"
        key: foundry-${{ hashFiles('Makefile', 'foundry.toml') }} # where fork block numbers & RPC are stored

    - name: Foundry compilation cache
      uses: actions/cache@v3
      with:
        path: |
          cache
          out
        key: ${{ github.base_ref || github.ref_name }}-foundry-${{ inputs.protocol }} # always keep compiled contracts from base branch

    - name: Run tests
      run: make ci > ${{ inputs.protocol }}.gasreport.ansi
      shell: bash
      env:
        PROTOCOL: ${{ inputs.protocol }}
        NETWORK: ${{ inputs.network }}
        ALCHEMY_KEY: ${{ inputs.alchemyKey }}

    - name: Compare gas reports
      uses: Rubilmax/foundry-gas-report@v3.3
      with:
        workflowId: ci-foundry-${{ inputs.protocol }}.yml
        report: ${{ inputs.protocol }}.gasreport.ansi
        ignore: test-foundry/**/*
        title: Morpho-${{ inputs.protocol }} gas impacts (${{ inputs.network }})
      id: gas_diff

    - name: Add gas diff to sticky comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: ${{ inputs.protocol }} (${{ inputs.network }})
        message: ${{ steps.gas_diff.outputs.markdown }}
