name: Solidity tests with Foundry

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Node dependencies cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: make ci
        env:
          NETWORK: eth-mainnet
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
