name: Solidity tests on Morpho Aave V3

on:
  push:
    branches:
      - main
    paths:
      - "lib/**"
      - "config/**"
      - "contracts/common/**"
      - "contracts/aave-v3/**"
      - "test/**"
      - "test-foundry/common/**"
      - "test-foundry/aave-v3/**"
      - "*.lock"
      - "Makefile"
      - "remappings.txt"
      - ".github/workflows/ci-foundry-aave-v3.yml"
  pull_request:
    paths:
      - "lib/**"
      - "config/**"
      - "contracts/common/**"
      - "contracts/aave-v3/**"
      - "test/**"
      - "test-foundry/common/**"
      - "test-foundry/aave-v3/**"
      - "*.lock"
      - "Makefile"
      - "remappings.txt"
      - ".github/workflows/ci-foundry-aave-v3.yml"

jobs:
  morpho-aave-v3:
    if: "! github.event.pull_request.draft"
    name: Morpho-Aave V3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Node dependencies cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: make test PROTOCOL=aave-v3
        env:
          NETWORK: avalanche-mainnet
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
